<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>Blackcatz1911</Authors>
    <Version>1.2.6.0</Version>
    <Description>Figure out what to do with all the ingame currencies.</Description>
    <PackageProjectUrl>https://github.com/Blackcatz1911/CurrencySpender</PackageProjectUrl>
    <RepoUrl>https://github.com/Blackcatz1911/CurrencySpender</RepoUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Platforms>x64</Platforms>
    <AssemblyVersion>1.2.6.0</AssemblyVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Include="..\CHANGELOG.md">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>true</Visible>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="ECommons" Version="3.2.1.6" />
    <PackageReference Remove="DotNet.ReproducibleBuilds" />
    <PackageReference Remove="DalamudPackager" />
  </ItemGroup>

  <Target Name="Message" BeforeTargets="BeforeBuild">
    <Message Text="Dalamud.Plugin: root at $(DalamudLibPath)" Importance="high" />
  </Target>
</Project>
